services:
  postgres_db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5643:5432"
    volumes:
      - ./container:/var/lib/postgresql/16/data